// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZdgaEtqvHrQXgQZ063gpz8u5VOYkho9A',
    appId: '1:125292045998:android:8d46156f8c44151ed32f3f',
    messagingSenderId: '125292045998',
    projectId: 'fireworks-a1b65',
    databaseURL: 'https://fireworks-a1b65-default-rtdb.firebaseio.com',
    storageBucket: 'fireworks-a1b65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH9h54vUFTTtwH4UhxDxRhoIfz-vbYRto',
    appId: '1:125292045998:ios:20b21859ff5dcde7d32f3f',
    messagingSenderId: '125292045998',
    projectId: 'fireworks-a1b65',
    databaseURL: 'https://fireworks-a1b65-default-rtdb.firebaseio.com',
    storageBucket: 'fireworks-a1b65.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

}